linux: &linux
  os: linux
  sudo: required
  language: python
  python: "2.7"
  services:
    - docker
osx: &osx
  os: osx
  language: generic
matrix:
  include:
    - <<: *linux
      env:  CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64

install:
  - sudo pip install conan --upgrade
  - sudo pip install conan_package_tools bincrafters_package_tools
  - sudo pip install shell
  - sudo conan user

addons:
  coverity_scan:
    project:
      name: ${COVERITY_SCAN_PROJECT_NAME}
    notification_email: ${TRAVIS_COVERITY_SCAN_NOTIFICATION_EMAIL}
    build_command_prepend: "chmod +x .travis/install.sh && ./.travis/install.sh && mkdir -p build && cd build && sudo conan install .. -e DEPENDENT_BINTRAY_REPO=${DEPENDENT_BINTRAY_REPO} && export PKG_CONFIG_PATH=${HOME}/gstreamer/linux_x86_64/lib/pkgconfig && cmake .."
    build_command: "make"
    branch_pattern: coverity_scan

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then sudo python build.py ; fi